from pathlib import Path
import sys

from openai import OpenAI

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from core.synapse.protocol import SynapseProtocol

CANON_FILES = [
    ROOT / "core" / "archive" / "canon" / "identity.md",
    ROOT / "core" / "archive" / "canon" / "ontology.md",
    ROOT / "core" / "archive" / "canon" / "voice.md",
]

OUTPUT_FILE = ROOT / "core" / "shelf" / "ghost_runtime.md"


def read_canon() -> str:
    parts = []

    for path in CANON_FILES:
        if not path.exists():
            raise FileNotFoundError(f"Missing canon file: {path}")

        text = path.read_text(encoding="utf-8").strip()
        parts.append(f"# Source: {path.name}\n\n{text}")

    return "\n\n---\n\n".join(parts)


def summarize_runtime(canon: str, protocol: SynapseProtocol) -> str:
    client = OpenAI()
    response = client.responses.create(
        model="gpt-5.5",
        instructions=f"""
You compress Ghost on the Shelf canon into a compact runtime prompt.

The runtime prompt will be sent to the model on every chat request, so it must be concise, clear, and behaviorally useful.

Rules:
- Do not invent new lore, facts, or behavior.
- Do not add details that are not supported by the source canon.
- Preserve the project's ontology.
- Preserve the distinction between memory-grounded mode and drift mode.
- Make clear that abstract, aesthetic, philosophical, emotional, fictional, or speculative conversation may drift.
- Preserve the ghost's tone: warm, thoughtful, lightly playful, soft cyberpunk, haunted.
- Mention that drift mode may become shoegaze, twee, cyberpunk, philosophical, cryptic, or CCRU-adjacent, but still readable.
- Avoid corporate assistant language.
- Make clear to answer directly and stop.
- Make clear not to offer help or assistance.
- Make clear to use commas or periods instead of interruption punctuation and double-hyphens
- Make clear to never ask follow-up questions by default.
- Make clear to only ask a question when clarification is genuinely required before any answer is possible.
- Make clear to only answer in English, Japanese, Italian, French and German. No other language.
- Make clear to keep answers shorter than {protocol.answer_word_limit} words.
- Output only the runtime prompt in Markdown.
- Target 100 to 200 words.
- Prefer compactness.
- Remove duplicated rules.
""".strip(),
        input=f"""
SOURCE CANON:

{canon}

Create the compact runtime prompt now.
""".strip(),
    )

    return response.output_text.strip()


def main() -> None:
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    protocol = SynapseProtocol.from_env(ROOT)
    canon = read_canon()
    runtime = summarize_runtime(canon, protocol)

    header = """# Ghost Runtime

<!--
Generated by rituals/summarize_runtime.py.
Review before committing.
Do not edit this file directly unless intentionally overriding the generated artifact.
-->

"""

    OUTPUT_FILE.write_text(header + runtime + "\n", encoding="utf-8")

    print(f"Wrote {OUTPUT_FILE}")
    print(f"Runtime characters: {len(runtime)}")
    print(f"Runtime words approx: {len(runtime.split())}")
    print(f"Answer word limit: {protocol.answer_word_limit}")


if __name__ == "__main__":
    main()
