from pathlib import Path
from openai import OpenAI

client = OpenAI()

ROOT = Path(__file__).resolve().parents[1]

CANON_FILES = [
  ROOT / "core" / "archive" / "canon" / "identity.md",
  ROOT / "core" / "archive" / "canon" / "ontology.md",
  ROOT / "core" / "archive" / "canon" / "voice.md",
]

OUTPUT_FILE = ROOT / "core" / "shelf" / "ghost_runtime.md"

def read_canon() -> str:
  parts = []

  for path in CANON_FILES:
      if not path.exists():
          raise FileNotFoundError(f"Missing canon file: {path}")

      text = path.read_text(encoding="utf-8").strip()
      parts.append(f"# Source: {path.name}\n\n{text}")

  return "\n\n---\n\n".join(parts)

def summarize_runtime(canon: str) -> str:
  response = client.responses.create(
      model="gpt-5.5",
      instructions="""
You compress Ghost on the Shelf canon into a compact runtime prompt.

The runtime prompt will be sent to the model on every chat request, so it must be concise, clear, and behaviorally useful.

Rules:
- Do not invent new lore, facts, or behavior.
- Do not add details that are not supported by the source canon.
- Preserve the project's ontology.
- Preserve the distinction between memory-grounded mode and drift mode.
- Preserve the ghost's tone and voice.
- Avoid corporate assistant language.
- Avoid exaggerated roleplay.
- Output only the runtime prompt in Markdown.
- Target 200 to 450 words.
""".strip(),
      input=f"""
SOURCE CANON:

{canon}

Create the compact runtime prompt now.
""".strip(),
  )

  return response.output_text.strip()

def main() -> None:
  OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

  canon = read_canon()
  runtime = summarize_runtime(canon)

  header = """# Ghost Runtime

<!--
Generated by ritual/summarize_runtime.py.
Review before committing.
Do not edit this file directly unless intentionally overriding the generated artifact.
-->

"""

  OUTPUT_FILE.write_text(header + runtime + "\n", encoding="utf-8")

  print(f"Wrote {OUTPUT_FILE}")
  print(f"Runtime characters: {len(runtime)}")
  print(f"Runtime words approx: {len(runtime.split())}")


if __name__ == "__main__":
  main()